language: python

python:
  - 3.6

service:
  - postgresql

before_script:
  - psql -c 'create database parkour;' -U postgres
  - mkdir /home/travis/build/maxplanck-ie/parkour/logs

install:
  - pip install -r requirements/prod.txt

script:
  - python manage.py test

notifications:
  email: false
